// Tanıtım sunumlarındaki örnek antrenör raporunun QR kodları bu kayıtları açar.
// Buradaki sporcular kurgudur; gerçek kullanıcı verisi içermez.
export interface DemoYoujiReport {
  id: string;
  fullName: string;
  birthYear: number;
  club: string;
  group: string;
  sport: string;
  measurementDate: string;
  height: number;
  weight: number;
  bmi: number;
  ffmi: number;
  bodyFatPercent: number;
  mineralAmount: number;
  proteinAmount: number;
}

export const DEMO_YOUJI_REPORTS: DemoYoujiReport[] = [
  {
    id: "basketbol-0",
    fullName: "Kerem Aydınlı",
    birthYear: 2010,
    club: "Anadolu Yıldızları Basketbol Kulübü",
    group: "U16 Erkek · A Takımı",
    sport: "Basketbol",
    measurementDate: "2026-09-04",
    height: 183,
    weight: 73.4,
    bmi: 21.9,
    ffmi: 19.6,
    bodyFatPercent: 9.5,
    mineralAmount: 3.4,
    proteinAmount: 13.3,
  },
  {
    id: "basketbol-1",
    fullName: "Mert Sönmez",
    birthYear: 2010,
    club: "Anadolu Yıldızları Basketbol Kulübü",
    group: "U16 Erkek · A Takımı",
    sport: "Basketbol",
    measurementDate: "2026-09-04",
    height: 191,
    weight: 76.8,
    bmi: 21.1,
    ffmi: 19.4,
    bodyFatPercent: 11.2,
    mineralAmount: 3.8,
    proteinAmount: 11.5,
  },
  {
    id: "basketbol-2",
    fullName: "Ali Efe Karabulut",
    birthYear: 2010,
    club: "Anadolu Yıldızları Basketbol Kulübü",
    group: "U16 Erkek · A Takımı",
    sport: "Basketbol",
    measurementDate: "2026-09-04",
    height: 192,
    weight: 80.8,
    bmi: 21.9,
    ffmi: 21.2,
    bodyFatPercent: 10.2,
    mineralAmount: 3.6,
    proteinAmount: 13.1,
  },
  {
    id: "basketbol-3",
    fullName: "Yiğit Arslan",
    birthYear: 2010,
    club: "Anadolu Yıldızları Basketbol Kulübü",
    group: "U16 Erkek · A Takımı",
    sport: "Basketbol",
    measurementDate: "2026-09-04",
    height: 196,
    weight: 73.9,
    bmi: 19.2,
    ffmi: 21.5,
    bodyFatPercent: 13.2,
    mineralAmount: 3.9,
    proteinAmount: 13.2,
  },
  {
    id: "basketbol-4",
    fullName: "Emir Doğancan",
    birthYear: 2010,
    club: "Anadolu Yıldızları Basketbol Kulübü",
    group: "U16 Erkek · A Takımı",
    sport: "Basketbol",
    measurementDate: "2026-09-04",
    height: 196,
    weight: 71.7,
    bmi: 18.7,
    ffmi: 20,
    bodyFatPercent: 11.9,
    mineralAmount: 3.2,
    proteinAmount: 11.2,
  },
  {
    id: "basketbol-5",
    fullName: "Baran Yılmazer",
    birthYear: 2011,
    club: "Anadolu Yıldızları Basketbol Kulübü",
    group: "U16 Erkek · A Takımı",
    sport: "Basketbol",
    measurementDate: "2026-09-04",
    height: 187,
    weight: 81.3,
    bmi: 23.2,
    ffmi: 20.6,
    bodyFatPercent: 10,
    mineralAmount: 3.6,
    proteinAmount: 11.5,
  },
  {
    id: "basketbol-6",
    fullName: "Tuna Özkaya",
    birthYear: 2010,
    club: "Anadolu Yıldızları Basketbol Kulübü",
    group: "U16 Erkek · A Takımı",
    sport: "Basketbol",
    measurementDate: "2026-09-04",
    height: 183,
    weight: 78.5,
    bmi: 23.4,
    ffmi: 22.2,
    bodyFatPercent: 13.4,
    mineralAmount: 3.5,
    proteinAmount: 13.8,
  },
  {
    id: "basketbol-7",
    fullName: "Deniz Akbulut",
    birthYear: 2011,
    club: "Anadolu Yıldızları Basketbol Kulübü",
    group: "U16 Erkek · A Takımı",
    sport: "Basketbol",
    measurementDate: "2026-09-04",
    height: 184,
    weight: 76.9,
    bmi: 22.7,
    ffmi: 19.7,
    bodyFatPercent: 11.8,
    mineralAmount: 3.5,
    proteinAmount: 10.6,
  },
  {
    id: "voleybol-0",
    fullName: "Zeynep Naz Ergin",
    birthYear: 2011,
    club: "Ege Fırtınası Voleybol Kulübü",
    group: "U16 Kız · A Takımı",
    sport: "Voleybol",
    measurementDate: "2026-09-05",
    height: 180,
    weight: 65.2,
    bmi: 20.1,
    ffmi: 19.4,
    bodyFatPercent: 22.8,
    mineralAmount: 2.9,
    proteinAmount: 9,
  },
  {
    id: "voleybol-1",
    fullName: "Elif Su Tanrıöver",
    birthYear: 2011,
    club: "Ege Fırtınası Voleybol Kulübü",
    group: "U16 Kız · A Takımı",
    sport: "Voleybol",
    measurementDate: "2026-09-05",
    height: 170,
    weight: 59.3,
    bmi: 20.5,
    ffmi: 18.9,
    bodyFatPercent: 24.2,
    mineralAmount: 2.5,
    proteinAmount: 9.2,
  },
  {
    id: "voleybol-2",
    fullName: "Defne Kılıçarslan",
    birthYear: 2011,
    club: "Ege Fırtınası Voleybol Kulübü",
    group: "U16 Kız · A Takımı",
    sport: "Voleybol",
    measurementDate: "2026-09-05",
    height: 173,
    weight: 65.7,
    bmi: 22,
    ffmi: 17.9,
    bodyFatPercent: 20.3,
    mineralAmount: 3,
    proteinAmount: 10.1,
  },
  {
    id: "voleybol-3",
    fullName: "İrem Balaban",
    birthYear: 2011,
    club: "Ege Fırtınası Voleybol Kulübü",
    group: "U16 Kız · A Takımı",
    sport: "Voleybol",
    measurementDate: "2026-09-05",
    height: 174,
    weight: 61.6,
    bmi: 20.3,
    ffmi: 17.1,
    bodyFatPercent: 20.5,
    mineralAmount: 3.2,
    proteinAmount: 8.2,
  },
  {
    id: "voleybol-4",
    fullName: "Melis Yörük",
    birthYear: 2010,
    club: "Ege Fırtınası Voleybol Kulübü",
    group: "U16 Kız · A Takımı",
    sport: "Voleybol",
    measurementDate: "2026-09-05",
    height: 179,
    weight: 57.1,
    bmi: 17.8,
    ffmi: 17.4,
    bodyFatPercent: 17.9,
    mineralAmount: 3.1,
    proteinAmount: 10.8,
  },
  {
    id: "voleybol-5",
    fullName: "Ada Gülcemal",
    birthYear: 2010,
    club: "Ege Fırtınası Voleybol Kulübü",
    group: "U16 Kız · A Takımı",
    sport: "Voleybol",
    measurementDate: "2026-09-05",
    height: 184,
    weight: 67.8,
    bmi: 20,
    ffmi: 17.5,
    bodyFatPercent: 23,
    mineralAmount: 2.9,
    proteinAmount: 8.9,
  },
  {
    id: "voleybol-6",
    fullName: "Ecrin Sarıtaş",
    birthYear: 2011,
    club: "Ege Fırtınası Voleybol Kulübü",
    group: "U16 Kız · A Takımı",
    sport: "Voleybol",
    measurementDate: "2026-09-05",
    height: 173,
    weight: 65.9,
    bmi: 22,
    ffmi: 16.9,
    bodyFatPercent: 17.6,
    mineralAmount: 3.2,
    proteinAmount: 10.2,
  },
  {
    id: "voleybol-7",
    fullName: "Duru Işıkdemir",
    birthYear: 2011,
    club: "Ege Fırtınası Voleybol Kulübü",
    group: "U16 Kız · A Takımı",
    sport: "Voleybol",
    measurementDate: "2026-09-05",
    height: 178,
    weight: 56.3,
    bmi: 17.8,
    ffmi: 16.9,
    bodyFatPercent: 20.7,
    mineralAmount: 2.8,
    proteinAmount: 10.5,
  },
];

export function getDemoYoujiReport(id: string): DemoYoujiReport | undefined {
  return DEMO_YOUJI_REPORTS.find((report) => report.id === id);
}

// Cihaz raporundaki türev değerler tek yerde hesaplanır; sayfa ile liste aynı sonucu verir.
export function calculateDemoBodyComposition(report: DemoYoujiReport) {
  const fatMass = (report.weight * report.bodyFatPercent) / 100;
  const leanMass = report.weight - fatMass;
  return {
    fatMass,
    leanMass,
    muscleMass: leanMass * 0.85,
    bodyWater: leanMass * 0.72,
    basalMetabolicRate: Math.round(370 + 21.6 * leanMass),
  };
}
